name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # Сборка будет запускаться только когда ты создаешь тег версии (например, v0.9.0)

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend (Vite)
        run: npm run build

      - name: Build and Publish (Electron)
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Это нужно для загрузки .exe в Releases